spring:
  application:
    name: SimpleBoard

  datasource:
    url: jdbc:h2:tcp://localhost/~/simpleboard
    #    url: jdbc:h2:mem:simpleboard
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs  # Swagger JSON 문서 위치
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 접속 경로
    operationsSorter: method  # 메서드 정렬 방식: a-z / method / alpha
    tagsSorter: alpha         # 태그 정렬 방식
    display-request-duration: true  # 요청 시간 표시 여부

  default-consumes-media-type: application/json
  default-produces-media-type: application/json

  info:
    title: SimpleBoard API 문서
    description: 게시판 프로젝트의 REST API 명세서입니다.
    version: v1.0.0